# Generated by Django 2.1.5 on 2020-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yyyyy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='商品名')),
                ('small_image', models.ImageField(upload_to='drug_img/%Y/%m/%d/', verbose_name='商品图片')),
            ],
        ),
    ]
