# Generated by Django 2.1.5 on 2020-07-29 11:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myusertwommmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=500, null=True, verbose_name='微信openid')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信名')),
                ('gender', models.CharField(blank=True, max_length=2, null=True, verbose_name='性别')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=200, null=True, verbose_name='省')),
                ('contry', models.CharField(blank=True, max_length=200, null=True, verbose_name='国家')),
                ('avatarurl', models.CharField(blank=True, max_length=2000, null=True, verbose_name='微信头像URL')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('c_time', models.DateTimeField(auto_now=True, null=True, verbose_name='添加时间')),
                ('user_type', models.IntegerField(blank=True, choices=[(1, '普通用户'), (2, '普通会员'), (3, '白金会员'), (4, '黄金会员')], null=True, verbose_name='用户等级')),
                ('token', models.CharField(blank=True, max_length=3000, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='token添加时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
