# Generated by Django 2.1.5 on 2020-07-29 16:20

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_myusertwommmm'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCategorymmmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GProductmmmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='商品名')),
                ('small_image', models.ImageField(upload_to='drug_img/%Y/%m/%d/', verbose_name='商品图片')),
                ('price', models.IntegerField(blank=True, default=89, null=True, verbose_name='现价')),
                ('origin_price', models.IntegerField(blank=True, default=99, null=True, verbose_name='原价')),
                ('spec', models.TextField(blank=True, default='None', null=True, verbose_name='简述')),
                ('total_sales', models.IntegerField(blank=True, default=0, null=True, verbose_name='销量')),
                ('vip_price', models.IntegerField(blank=True, default=79, null=True, verbose_name='会员价')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='商品详细说明')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.GCategorymmmm', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'ordering': ['id'],
            },
        ),
    ]
