# Generated by Django 2.1.5 on 2020-08-04 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_gcategorymmmm_gproductmmmm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(blank=True, max_length=60, null=True, verbose_name='收货人')),
                ('aphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('city', models.CharField(blank=True, max_length=500, null=True, verbose_name='省市')),
                ('aaddress', models.CharField(blank=True, max_length=500, null=True, verbose_name='详细地址')),
                ('adefaultaddress', models.CharField(default='2', max_length=5, verbose_name='是否默认地址')),
                ('auser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressextension', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
