# Generated by Django 2.1.5 on 2020-08-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_ddaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddaddress',
            name='auser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressextension', to='backend.myusertwommmm', verbose_name='用户'),
        ),
    ]
