# Generated by Django 2.1.5 on 2020-08-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200804_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ddaddress',
        ),
    ]
