# Generated by Django 2.1.5 on 2020-08-05 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200804_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='wxdindan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxopenid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='用户openid')),
                ('wxusertext', models.CharField(blank=True, max_length=1000, null=True, verbose_name='用户留言')),
                ('fapiao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='发票抬头')),
                ('fapiaohaoma', models.CharField(blank=True, max_length=1000, null=True, verbose_name='发票税号')),
                ('paymode', models.CharField(blank=True, default='1', max_length=1000, null=True, verbose_name='支付方式')),
                ('productid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='商品id')),
                ('count', models.CharField(blank=True, max_length=1000, null=True, verbose_name='购买数量')),
                ('payzt', models.CharField(blank=True, max_length=1000, null=True, verbose_name='支付状态')),
                ('dindanbianhao', models.CharField(blank=True, max_length=200, null=True, verbose_name='订单编号')),
                ('totalprice', models.CharField(blank=True, max_length=200, null=True, verbose_name='总货款')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='提交订单时间')),
                ('addressid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dindanaddressextension', to='backend.ddaddress')),
                ('wxuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wxdindanextension', to='backend.myusertwommmm', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'ordering': ['id'],
            },
        ),
    ]
